// <auto-generated />
using System;
using CajemesFoodAlejandro_Aimara.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CajemesFoodAlejandro_Aimara.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CajemesFoodAlejandro_Aimara.Data.Models.Administrador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("CajemesFoodAlejandro_Aimara.Data.Models.Local", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Administradorid")
                        .HasColumnType("int");

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Administradorid");

                    b.ToTable("Locals");
                });

            modelBuilder.Entity("CajemesFoodAlejandro_Aimara.Data.Models.Local_Platillo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Localid")
                        .HasColumnType("int");

                    b.Property<int>("Platilloid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Localid");

                    b.HasIndex("Platilloid");

                    b.ToTable("Local_Platillo");
                });

            modelBuilder.Entity("CajemesFoodAlejandro_Aimara.Data.Models.Platillo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("caducidad")
                        .HasColumnType("datetime2");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("precio")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Platillos");
                });

            modelBuilder.Entity("CajemesFoodAlejandro_Aimara.Data.Models.Local", b =>
                {
                    b.HasOne("CajemesFoodAlejandro_Aimara.Data.Models.Administrador", "Administrador")
                        .WithMany("Local")
                        .HasForeignKey("Administradorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("CajemesFoodAlejandro_Aimara.Data.Models.Local_Platillo", b =>
                {
                    b.HasOne("CajemesFoodAlejandro_Aimara.Data.Models.Local", "Local")
                        .WithMany("Local_Platillo")
                        .HasForeignKey("Localid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CajemesFoodAlejandro_Aimara.Data.Models.Platillo", "Platillo")
                        .WithMany("Local_Platillo")
                        .HasForeignKey("Platilloid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Platillo");
                });

            modelBuilder.Entity("CajemesFoodAlejandro_Aimara.Data.Models.Administrador", b =>
                {
                    b.Navigation("Local");
                });

            modelBuilder.Entity("CajemesFoodAlejandro_Aimara.Data.Models.Local", b =>
                {
                    b.Navigation("Local_Platillo");
                });

            modelBuilder.Entity("CajemesFoodAlejandro_Aimara.Data.Models.Platillo", b =>
                {
                    b.Navigation("Local_Platillo");
                });
#pragma warning restore 612, 618
        }
    }
}
